from setuptools import setup, find_packages

setup(
    name="afq_insight_experiments",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.24.0,<2.0.0",
        "matplotlib>=3.7.0",
        "pandas>=2.0.0",
        "seaborn>=0.12.0",
        "scikit-learn>=1.3.0",
        "afqinsight>=0.3.0",
        "jupyter>=1.0.0",
        "ipywidgets>=8.0.0",
        "tqdm>=4.65.0",
        "pytest>=7.0.0",
        "setuptools>=65.0.0",
    ],
    author="Sam Chou",
    author_email="sam@thechous.com",
    description="Autoencoder experiments for AFQ-Insight neuroimaging data analysis",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    keywords="autoencoder, VAE, afq, neuroimaging, diffusion MRI, brain connectivity",
    url="https://github.com/yourusername/AFQ-Insight-Autoencoder-Experiments",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
    ],
    python_requires=">=3.8",
) 